language: generic 

sudo: required

service:
  - docker

before_install:
  - docker build -t bugrahan23/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true bugrahan23/docker-react npm run test



